### ISSUE TITLE
minimumPowerUpSizeBabz returns incorrect value

### ISSUE THREAD

**Issue by troggy** [acebusters/acebusters-economy#70]
It works well only for the very first power up. For the subsequent once it will return incorrect value, cause it doesn't consider power pool (and it should).

The formula for minimumPowerUpSizeBabz is much complex then it is now in the code. Unfortunately it was lost in the Slack archives

This is low priority thing cause `minimumPowerUpSizeBabz` is not affecting how contracts work and just used as a UI convenience on the frontend

**Comment by bkcninja** [comment]
I just looked into this issue. We have only one relevant check in our powerUp function 
`powBal >= authorizedPow.div(MIN_SHARE_OF_POWER)`

And this is really not a check. Once someone has power equal to 
`authorizedPow.div(MIN_SHARE_OF_POWER)`
the minPowerUpSizeBabz for him comes down to 0 IF we start considering existing shares.
So instead of having someone power Up completeSupply() / MIN_SHARE_OF_POWER which would grow as the economy grows, we could just have them power a minimum amount of nutz, which can just be set in the power Up.

I have commented on #56, we could just use that solution. @troggy what do you think? Is there some blocker for implementing #56?

**Comment by troggy** [comment]
the whole "min share" idea was about prevention of possible rounding errors. I don't get how are they possible. If there is no problem with rounding we can just remove the limit altogether and allow to power up any amount
